apiVersion: apps/v1
kind: Deployment
metadata:
  # tên của deployment
  name: audeployapp
  labels:
    track: canary
spec:
  # số POD tạo ra
  replicas: 1
  # thiết lập các POD do deploy quản lý, là POD có nhãn  "app=deployapp"
  selector:
    matchLabels:
      app: au-service
  # Định nghĩa mẫu POD, khi cần Deploy sử dụng mẫu này để tạo Pod
  template:
    metadata:
      labels:
        app: au-service
    spec:
      containers:
        - name: au-service
          image: au-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5003
          env:
            - name: DB_URL
              value: xxx
          imagePullPolicy: Always
