spring:
  application:
    name: player
  datasource:
    url: jdbc:mysql://localhost:3306/audb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  servlet:
    context-path: /player
  port: 5004

kafka:
  bootstrapAddress: localhost:9092

apiVersion: 1
