---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: middleware
    app: registry
  name: registry
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  selector:
    project: piggymetrics
    tier: middleware
    app: registry
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: middleware
    app: registry
  name: registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: middleware
        app: registry
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        image: ${CONTAINER_REGISTRY}.azurecr.io/piggymetrics-registry:${IMAGE_TAG}
        name: registry
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
status: {}