---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: frontend
    app: gateway
  name: gateway
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 4000
  selector:
    project: piggymetrics
    tier: frontend
    app: gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  labels:
    project: piggymetrics
    tier: frontend
    app: gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        project: piggymetrics
        tier: frontend
        app: gateway
    spec:
      containers:
      - name: gateway
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        image: ${CONTAINER_REGISTRY}.azurecr.io/piggymetrics-gateway:${IMAGE_TAG}
        ports:
        - containerPort: 4000
      restartPolicy: Always