---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: account-service
  name: account-service
spec:
  ports:
  - name: http
    port: 6000
    targetPort: 6000
  selector:
    project: piggymetrics
    tier: backend
    app: account-service
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: account-service
  name: account-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: backend
        app: account-service
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        - name: ACCOUNT_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: account_service_password
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: mongodb_database
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: mongodb_uri
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_host
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_port
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_password
        ports:
          - containerPort: 6000
        image: ${CONTAINER_REGISTRY}.azurecr.io/piggymetrics-account-service:${IMAGE_TAG}
        name: account-service
      restartPolicy: Always