spring:
  application:
    name: club
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest

server:
  servlet:
    context-path: /club
  port: 5008

jsa:
    rabbitmq:
        exchange: eda.exchange.event


