spring:
  application:
    name: order
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
#spring:
#  rabbitmq:
#    listener:
#      simple:
#        retry:
#          enabled: true
#          initial-interval: 3s
#          max-attempts: 5
#          max-interval: 10s
#          multiplier: 2

server:
  servlet:
    context-path: /order
  port: 5009

jsa:
    rabbitmq:
        queue: player
