version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./zk-single-kafka-single/zookeeper/data:/data
      - ./zk-single-kafka-single/zookeeper/datalog:/datalog
    networks:
      - ui-network
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:19092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >
        fb-event.match-scheduled:1:1,
        fb-event.match-started:1:1,
        fb-event.goal-scored:1:1,
        fb-event.card-received:1:1,
        fb-event.match-finished:1:1,
        fb-event.player-started-career:1:1,
        fb-view.match-score:1:1,
        fb-view.team-ranking:1:1,
        fb-view.player-goals:1:1,
        fb-view.player-cards:1:1,
        fb-view.top-players:1:1,
        fb-connect.public.players:1:1
      KAFKA_BROKER_ID: 999
    volumes:
      - ./zk-single-kafka-single/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - ui-network

  db-pg:
    container_name: db-pg
    image: debezium/example-postgres:1.7
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - ui-network

  connect:
    container_name: connect
    image: debezium/connect:1.7
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - db-pg
    environment:
      - BOOTSTRAP_SERVERS=kafka:19092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=fb.connect.configs
      - OFFSET_STORAGE_TOPIC=fb.connect.offsets
    networks:
      - ui-network

  debezium-ui:
    container_name: debezium-ui
    image: debezium/debezium-ui:1.7
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CONNECT_URI=http://connect:8083
    depends_on:
      - connect
    networks:
      - ui-network

networks:
  ui-network:
    external: false