spring:
  application:
    name: match
#  datasource:
#    url: jdbc:mysql://localhost:3306/audb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

server:
  servlet:
    context-path: /match
  port: 5005


kafka:
  bootstrapAddress: localhost:9092

apiVersion: 1
